# Generated by Django 6.0.2 on 2026-02-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='RestaurantName')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='ContactNumber')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
