# Generated by Django 6.0.2 on 2026-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='has_delivery',
            field=models.BooleanField(default=True, verbose_name='delivery service'),
        ),
    ]
