# Generated by Django 5.2.1 on 2026-02-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_restaurant_has_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created At'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='has_delivery',
            field=models.BooleanField(default=True, verbose_name='Has Delivery'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Contact Number'),
        ),
    ]
