# Generated by Django 6.0.2 on 2026-02-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_menucategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='RestaurantName')),
                ('owner_name', models.CharField(max_length=100, verbose_name='RestaurantOwnerName')),
                ('email', models.EmailField(max_length=100, verbose_name='OwnerEmail')),
                ('phone_number', models.CharField(max_length=50, verbose_name='OwnerContactNumber')),
                ('address', models.TextField(verbose_name='OwnerAddress')),
                ('city', models.CharField(max_length=100, verbose_name='OwnerCityAddress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
