# Generated by Django 6.0.2 on 2026-02-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_restaurant_options_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
