# Generated by Django 6.0.2 on 2026-02-17 03:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='customer_id')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='customer_name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='customer_phone')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='customer_Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='customer_created_at')),
            ],
        ),
    ]
