# Generated by Django 6.0.2 on 2026-02-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'customer_record'},
        ),
    ]
