# Generated by Django 6.0.2 on 2026-02-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='item_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='item_description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('is_available', models.BooleanField(default=True, verbose_name='available_item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='account.restaurant', verbose_name='restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
