# Generated by Django 5.2.1 on 2026-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_menuitem_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='featured_item'),
        ),
    ]
